export type MyTicketTypes = {
  buyer: string;
  buyerAddress: string;
  createdAt: Date;
  fiatPrice: any | null;
  iapOrderId: any | null;
  id: number;
  isRevealed: boolean;
  isSent: boolean;
  itemId: number;
  mysteryBoxId: number;
  mysteryboxInfo: any;
  mysteryboxItem: any;
  price: number;
  status: string;
  tokenId: number;
  txHash: string;
  updatedAt: Date;
  useDate: Date | null;
  usePoint: any | null;
  day?: string;
  location?: string;
  duration?: string;
  team?: string;
  quote?: string;
  sellbook?: {
    createdAt: Date;
    creatorFee: number;
    dropsId: number;
    endDate: Date;
    id: number;
    infoId: number;
    itemId: number;
    price: number;
    sellInfo: any;
    startDate: Date;
    team: string;
    tokenId: number;
    type: number;
    uid: string;
    updatedAt: Date;
    wallet: string;
  };
};
